{
 "title": "4RedTeam Service",
 "tags": [ "4RedTeam" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service_name", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  { "title": "Server resources utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage_percent{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "VIRT memory usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "RSS memory usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service_name=~\"$service_name\"}"
    }
   ]
  },
  { "title": "Golang runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "go_stack_inuse_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_stack_inuse_bytes{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "go_stack_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_stack_sys_bytes{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "go_cgo_calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(go_cgo_calls{service_name=~\"$service_name\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "go_goroutines{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "go_pause_gc_total_nanosec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(go_pause_gc_total_nanosec{service_name=~\"$service_name\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go_heap_objects_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_heap_objects_bytes{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "go_heap_allocs_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_heap_allocs_bytes{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "rate(go_total_allocs_bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(go_total_allocs_bytes{service_name=~\"$service_name\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go_heap_objects_counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "go_heap_objects_counter{service_name=~\"$service_name\"}"
    }
   ]
  }
 ]
}