// Code generated by Fern. DO NOT EDIT.

package client

import (
    annotationqueues "4redteam/pkg/observability/langfuse/api/annotationqueues"
    blobstorageintegrations "4redteam/pkg/observability/langfuse/api/blobstorageintegrations"
    comments "4redteam/pkg/observability/langfuse/api/comments"
    datasetitems "4redteam/pkg/observability/langfuse/api/datasetitems"
    datasetrunitems "4redteam/pkg/observability/langfuse/api/datasetrunitems"
    datasets "4redteam/pkg/observability/langfuse/api/datasets"
    health "4redteam/pkg/observability/langfuse/api/health"
    ingestion "4redteam/pkg/observability/langfuse/api/ingestion"
    llmconnections "4redteam/pkg/observability/langfuse/api/llmconnections"
    media "4redteam/pkg/observability/langfuse/api/media"
    metricsv2 "4redteam/pkg/observability/langfuse/api/metricsv2"
    metrics "4redteam/pkg/observability/langfuse/api/metrics"
    models "4redteam/pkg/observability/langfuse/api/models"
    observationsv2 "4redteam/pkg/observability/langfuse/api/observationsv2"
    observations "4redteam/pkg/observability/langfuse/api/observations"
    opentelemetry "4redteam/pkg/observability/langfuse/api/opentelemetry"
    organizations "4redteam/pkg/observability/langfuse/api/organizations"
    projects "4redteam/pkg/observability/langfuse/api/projects"
    promptversion "4redteam/pkg/observability/langfuse/api/promptversion"
    prompts "4redteam/pkg/observability/langfuse/api/prompts"
    scim "4redteam/pkg/observability/langfuse/api/scim"
    scoreconfigs "4redteam/pkg/observability/langfuse/api/scoreconfigs"
    scorev2 "4redteam/pkg/observability/langfuse/api/scorev2"
    score "4redteam/pkg/observability/langfuse/api/score"
    sessions "4redteam/pkg/observability/langfuse/api/sessions"
    trace "4redteam/pkg/observability/langfuse/api/trace"
    core "4redteam/pkg/observability/langfuse/api/core"
    internal "4redteam/pkg/observability/langfuse/api/internal"
    option "4redteam/pkg/observability/langfuse/api/option"
)


type Client struct {
    Annotationqueues *annotationqueues.Client
    Blobstorageintegrations *blobstorageintegrations.Client
    Comments *comments.Client
    Datasetitems *datasetitems.Client
    Datasetrunitems *datasetrunitems.Client
    Datasets *datasets.Client
    Health *health.Client
    Ingestion *ingestion.Client
    Llmconnections *llmconnections.Client
    Media *media.Client
    Metricsv2 *metricsv2.Client
    Metrics *metrics.Client
    Models *models.Client
    Observationsv2 *observationsv2.Client
    Observations *observations.Client
    Opentelemetry *opentelemetry.Client
    Organizations *organizations.Client
    Projects *projects.Client
    Promptversion *promptversion.Client
    Prompts *prompts.Client
    SCIM *scim.Client
    Scoreconfigs *scoreconfigs.Client
    Scorev2 *scorev2.Client
    Score *score.Client
    Sessions *sessions.Client
    Trace *trace.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
    options := core.NewRequestOptions(opts...)
    return &Client{
        Annotationqueues: annotationqueues.NewClient(options),
        Blobstorageintegrations: blobstorageintegrations.NewClient(options),
        Comments: comments.NewClient(options),
        Datasetitems: datasetitems.NewClient(options),
        Datasetrunitems: datasetrunitems.NewClient(options),
        Datasets: datasets.NewClient(options),
        Health: health.NewClient(options),
        Ingestion: ingestion.NewClient(options),
        Llmconnections: llmconnections.NewClient(options),
        Media: media.NewClient(options),
        Metricsv2: metricsv2.NewClient(options),
        Metrics: metrics.NewClient(options),
        Models: models.NewClient(options),
        Observationsv2: observationsv2.NewClient(options),
        Observations: observations.NewClient(options),
        Opentelemetry: opentelemetry.NewClient(options),
        Organizations: organizations.NewClient(options),
        Projects: projects.NewClient(options),
        Promptversion: promptversion.NewClient(options),
        Prompts: prompts.NewClient(options),
        SCIM: scim.NewClient(options),
        Scoreconfigs: scoreconfigs.NewClient(options),
        Scorev2: scorev2.NewClient(options),
        Score: score.NewClient(options),
        Sessions: sessions.NewClient(options),
        Trace: trace.NewClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

